task: 'metadrive_safe'
steps: 1.01e6
env_num: 8
eval_episode_num: 5
action_repeat: 1
train_ratio: 64
time_limit: 1000

seed: ${seed}
device: ${device}

metadrive_source: '/home/ac/@Lyz-Code/safeRL-metadrive/metadrive'
train_start_seed: 100
train_num_scenarios: 50
eval_start_seed: 1000
eval_num_scenarios: 10
extra_config: {}

encoder:
  mlp_keys: '^state$'
  cnn_keys: '$^'
decoder:
  mlp_keys: '^state$'
  cnn_keys: '$^'
